/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsSlugRouteImport } from './routes/cars_.$slug'
import { Route as ApiContentIslandSnapshotInfoRouteImport } from './routes/api.content-island.snapshot-info'
import { Route as ApiSnapshotRefreshRouteImport } from './routes/api.snapshot.refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars_/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentIslandSnapshotInfoRoute =
  ApiContentIslandSnapshotInfoRouteImport.update({
    id: '/api/content-island/snapshot-info',
    path: '/api/content-island/snapshot-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSnapshotRefreshRoute = ApiSnapshotRefreshRouteImport.update({
  id: '/api/snapshot/refresh',
  path: '/api/snapshot/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/api/content-island/snapshot-info': typeof ApiContentIslandSnapshotInfoRoute
  '/api/snapshot/refresh': typeof ApiSnapshotRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars': typeof CarsIndexRoute
  '/api/content-island/snapshot-info': typeof ApiContentIslandSnapshotInfoRoute
  '/api/snapshot/refresh': typeof ApiSnapshotRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars_/$slug': typeof CarsSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/api/content-island/snapshot-info': typeof ApiContentIslandSnapshotInfoRoute
  '/api/snapshot/refresh': typeof ApiSnapshotRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars/$slug'
    | '/cars/'
    | '/api/content-island/snapshot-info'
    | '/api/snapshot/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars/$slug'
    | '/cars'
    | '/api/content-island/snapshot-info'
    | '/api/snapshot/refresh'
  id:
    | '__root__'
    | '/'
    | '/cars_/$slug'
    | '/cars/'
    | '/api/content-island/snapshot-info'
    | '/api/snapshot/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsSlugRoute: typeof CarsSlugRoute
  CarsIndexRoute: typeof CarsIndexRoute
  ApiContentIslandSnapshotInfoRoute: typeof ApiContentIslandSnapshotInfoRoute
  ApiSnapshotRefreshRoute: typeof ApiSnapshotRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars_/$slug': {
      id: '/cars_/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-island/snapshot-info': {
      id: '/api/content-island/snapshot-info'
      path: '/api/content-island/snapshot-info'
      fullPath: '/api/content-island/snapshot-info'
      preLoaderRoute: typeof ApiContentIslandSnapshotInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot/refresh': {
      id: '/api/snapshot/refresh'
      path: '/api/snapshot/refresh'
      fullPath: '/api/snapshot/refresh'
      preLoaderRoute: typeof ApiSnapshotRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsSlugRoute: CarsSlugRoute,
  CarsIndexRoute: CarsIndexRoute,
  ApiContentIslandSnapshotInfoRoute: ApiContentIslandSnapshotInfoRoute,
  ApiSnapshotRefreshRoute: ApiSnapshotRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
